### ISSUE TITLE
 problems logging in 

### ISSUE THREAD

**Issue by marywoodtrust** [pH-7/Honeypots#1]
I am having problems logging in Please help . I try to enter my email address and press forgotten password and it does not work  I am now locked out!!  This is on joomla

**Comment by pH-7** [comment]
It's normal you can't logged in.
It's a fake login form, just to trap hackers (like a honeypot) and track their behaviours. 

More details: https://www.slideshare.net/PierreHenrySoria/protect-you-site-with-honeypots

P.S. That script is quite old and might not work with the latest Joomla version (I didn't check the newest Joomla versions).
